### PR TITLE
fix(pybitcoinkernel): add python cleanup function to pybitcoinkernel module

### LINKED ISSUE #368: Indirect leak on `kernel_block` target due to `pybitcoinkernel` when using parallelism
I just noticed that running the `kernel_block` target with `pybitcoinkernel` using, for example, the `-fork` option from libfuzzer makes the target to crash instantly. The crash happens due to an indirect leak:

```sh
Indirect leak of 524 byte(s) in 1 object(s) allocated from:
    #0 0x55e767d0d030 in realloc (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x152030) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #1 0x764f6961aaf5 in resize_compact /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/unicodeobject.c:1020:31
    #2 0x764f6964654c in _PyUnicodeWriter_Finish /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/unicodeobject.c:13315:16
    #3 0x764f69653521 in PyUnicode_Format /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/unicodeobject.c:14504:12
    #4 0x764f69562d98 in binary_op1 /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/abstract.c:882:13
    #5 0x764f69562d98 in binary_op /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/abstract.c:921:24
    #6 0x764f69562d98 in PyNumber_Remainder /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/abstract.c:1137:12
    #7 0x764f6951d194 in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:3382:19
    #8 0x764f6969d026 in builtin___build_class__ /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/bltinmodule.c:200:12
    #9 0x764f695dfadb in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/methodobject.c:438:24
    #10 0x764f69582b2b in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_call.h:92:11
    #11 0x764f69582b2b in PyObject_Vectorcall /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:325:12
    #12 0x764f6951d5ed in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:2706:19
    #13 0x764f696a091e in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_ceval.h:89:16
    #14 0x764f696a091e in _PyEval_Vector /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:1683:12
    #15 0x764f696a091e in PyEval_EvalCode /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:578:21
    #16 0x764f6969c8af in builtin_exec_impl /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/bltinmodule.c:1096:17
    #17 0x764f6969c8af in builtin_exec /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/clinic/bltinmodule.c.h:586:20
    #18 0x764f695dfadb in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/methodobject.c:438:24
    #19 0x764f69519deb in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:3254:26
    #20 0x764f69582d9d in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_call.h:92:11
    #21 0x764f69582d9d in object_vacall /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:850:14
    #22 0x764f69582fe0 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:911:24
    #23 0x764f696d8141 in import_find_and_load /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2779:11
    #24 0x764f696d8141 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2862:15
    #25 0x764f69523a6b in import_name /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:2482:15
    #26 0x764f69523a6b in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:2135:19
    #27 0x764f696a091e in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_ceval.h:89:16
    #28 0x764f696a091e in _PyEval_Vector /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:1683:12
    #29 0x764f696a091e in PyEval_EvalCode /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:578:21
    #30 0x764f6969c8af in builtin_exec_impl /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/bltinmodule.c:1096:17
    #31 0x764f6969c8af in builtin_exec /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/clinic/bltinmodule.c.h:586:20
    #32 0x764f695dfadb in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/methodobject.c:438:24
    #33 0x764f69519deb in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:3254:26
    #34 0x764f69582d9d in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_call.h:92:11
    #35 0x764f69582d9d in object_vacall /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:850:14
    #36 0x764f69582fe0 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:911:24
    #37 0x764f696d8141 in import_find_and_load /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2779:11
    #38 0x764f696d8141 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2862:15
    #39 0x764f69523a6b in import_name /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:2482:15
    #40 0x764f69523a6b in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:2135:19
    #41 0x764f696a091e in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_ceval.h:89:16
    #42 0x764f696a091e in _PyEval_Vector /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:1683:12
    #43 0x764f696a091e in PyEval_EvalCode /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:578:21
    #44 0x764f6969c8af in builtin_exec_impl /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/bltinmodule.c:1096:17
    #45 0x764f6969c8af in builtin_exec /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/clinic/bltinmodule.c.h:586:20
    #46 0x764f695dfadb in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/methodobject.c:438:24
    #47 0x764f69519deb in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:3254:26

Indirect leak of 520 byte(s) in 1 object(s) allocated from:
    #0 0x55e767d0cc28 in malloc (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x151c28) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #1 0x764f695ea30f in _PyObject_Malloc /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/obmalloc.c:1569:11
    #2 0x764f69729608 in gc_alloc /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Modules/gcmodule.c:2307:17
    #3 0x764f69729608 in _PyObject_GC_NewVar /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Modules/gcmodule.c:2341:25
    #4 0x764f695f6de7 in PyTuple_New /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/tupleobject.c:74:10
    #5 0x764f695f6de7 in PyTuple_New /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/tupleobject.c:68:1
    #6 0x764f696e95fa in r_object /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1217:13
    #7 0x764f696e98a7 in r_object /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1397:21
    #8 0x764f696e9626 in r_object /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1223:18
    #9 0x764f696e988c in r_object /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1394:22
    #10 0x764f696e9626 in r_object /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1223:18
    #11 0x764f696e988c in r_object /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1394:22
    #12 0x764f696eb89f in read_object /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1525:9
    #13 0x764f696ebb1c in marshal_loads_impl /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/marshal.c:1832:14
    #14 0x764f696ebb1c in marshal_loads /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/clinic/marshal.c.h:154:20
    #15 0x764f695207e5 in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:2904:19
    #16 0x764f69582d9d in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_call.h:92:11
    #17 0x764f69582d9d in object_vacall /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:850:14
    #18 0x764f69582fe0 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:911:24
    #19 0x764f696d8141 in import_find_and_load /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2779:11
    #20 0x764f696d8141 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2862:15
    #21 0x764f69699c36 in builtin___import___impl /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/bltinmodule.c:275:12
    #22 0x764f69699c36 in builtin___import__ /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/clinic/bltinmodule.c.h:107:20
    #23 0x764f695dfadb in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/methodobject.c:438:24
    #24 0x764f69519deb in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:3254:26
    #25 0x764f69582d9d in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_call.h:92:11
    #26 0x764f69582d9d in object_vacall /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:850:14
    #27 0x764f69582fe0 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:911:24
    #28 0x764f696d7fc3 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2931:25
    #29 0x764f69523a6b in import_name /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:2482:15
    #30 0x764f69523a6b in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:2135:19
    #31 0x764f696a091e in _PyEval_EvalFrame /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_ceval.h:89:16
    #32 0x764f696a091e in _PyEval_Vector /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:1683:12
    #33 0x764f696a091e in PyEval_EvalCode /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/ceval.c:578:21
    #34 0x764f6969c8af in builtin_exec_impl /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/bltinmodule.c:1096:17
    #35 0x764f6969c8af in builtin_exec /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/clinic/bltinmodule.c.h:586:20
    #36 0x764f695dfadb in cfunction_vectorcall_FASTCALL_KEYWORDS /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/methodobject.c:438:24
    #37 0x764f69519deb in _PyEval_EvalFrameDefault /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/Python/bytecodes.c:3254:26
    #38 0x764f69582d9d in _PyObject_VectorcallTstate /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Include/internal/pycore_call.h:92:11
    #39 0x764f69582d9d in object_vacall /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:850:14
    #40 0x764f69582fe0 in PyObject_CallMethodObjArgs /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/call.c:911:24
    #41 0x764f696d8141 in import_find_and_load /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2779:11
    #42 0x764f696d8141 in PyImport_ImportModuleLevelObject /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/import.c:2862:15

Indirect leak of 520 byte(s) in 1 object(s) allocated from:
    #0 0x55e767d0cc28 in malloc (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x151c28) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #1 0x764f695ea30f in _PyObject_Malloc /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/obmalloc.c:1569:11
    #2 0x764f69729608 in gc_alloc /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Modules/gcmodule.c:2307:17
    #3 0x764f69729608 in _PyObject_GC_NewVar /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Modules/gcmodule.c:2341:25
    #4 0x764f695f72b5 in _PyTuple_FromArray /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/tupleobject.c:378:28
    #5 0x764f695f72b5 in _PyTuple_FromArray /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Objects/tupleobject.c:372:1
    #6 0x764f6970f295 in list_builtin_module_names /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/sysmodule.c:2441:23
    #7 0x764f6970f295 in _PySys_InitCore /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/sysmodule.c:3302:5
    #8 0x764f6970f295 in _PySys_Create /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/sysmodule.c:3604:14
    #9 0x764f696f3805 in pycore_interp_init /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/pylifecycle.c:856:14
    #10 0x764f696f55cd in pyinit_config /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/pylifecycle.c:897:14
    #11 0x764f696f55cd in pyinit_core /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/pylifecycle.c:1060:18
    #12 0x764f696f5754 in Py_InitializeFromConfig /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/pylifecycle.c:1282:14
    #13 0x764f696f5754 in Py_InitializeFromConfig /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/pylifecycle.c:1267:1
    #14 0x764f696f69af in Py_InitializeEx /usr/src/python3.12-3.12.3-1ubuntu0.9/build-shared/../Python/pylifecycle.c:1320:14
    #15 0x55e767d5b63c in char* call_python_function<unsigned char const*, char*>(unsigned char const*, unsigned long, char const*, _object* (*)(unsigned char const*, unsigned long), char* (*)(_object*)) module.cpp
    #16 0x55e767d5b465 in block_parse(unsigned char const*, unsigned long) (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x1a0465) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #17 0x55e767d5c071 in bitcoinfuzz::module::Pybitcoinkernel::kernel_block[abi:cxx11](std::span<unsigned char const, 18446744073709551615ul>) const (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x1a1071) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #18 0x55e767fe6af5 in bitcoinfuzz::Driver::KernelBlockTarget(std::span<unsigned char const, 18446744073709551615ul>) const (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x42baf5) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #19 0x55e767fecf76 in bitcoinfuzz::Driver::Run(unsigned char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) const (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x431f76) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #20 0x55e767d52cd8 in LLVMFuzzerTestOneInput (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x197cd8) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #21 0x55e767c4ecef in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x93cef) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #22 0x55e767c4ff01 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x94f01) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #23 0x55e767c50590 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x95590) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #24 0x55e767c3cbe5 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x81be5) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #25 0x55e767c68ff6 in main (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0xadff6) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)
    #26 0x764f6902a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #27 0x764f6902a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #28 0x55e767c31024 in _start (/home/bruno/projects/bitcoinfuzz/bitcoinfuzz+0x76024) (BuildId: 1f149582967786d68f1fa0fe919d6d70e7d433bc)

SUMMARY: AddressSanitizer: 2382428 byte(s) leaked in 2176 allocation(s).
MS: 5 InsertRepeatedBytes-InsertRepeatedBytes-CrossOver-PersAutoDict-ShuffleBytes- DE: "\377\377\377\377"-; base unit: 73231e70e5b249c273f4768e1090b3b5eafb84fc
```

I just tested it by running with some suppresions and it worked fine:

```sh
cat > lsan.supp << EOF
leak:Python
leak:PyObject
EOF

LSAN_OPTIONS=suppressions=lsan.supp FUZZ=kernel_block ./bitcoinfuzz -fork=3
```

### PR DESCRIPTION
**Pull request by KY-U**
Closes #368

Added @erickcestari's [solution](https://github.com/bitcoinfuzz/bitcoinfuzz/pull/415#pullrequestreview-3759000511) for indirect leak on `kernel_block` target due to [`pybitcoinkernel`](https://github.com/bitcoinfuzz/bitcoinfuzz/blob/v2/modules/pybitcoinkernel/module.cpp)'s absence of cleanup routine.

### CODE REVIEW

File: modules/pybitcoinkernel/module.cpp [hunk 1]
```diff
@@ -1,19 +1,31 @@
...
 static ReturnType
 call_python_function(const InputType input, size_t input_len,
                      const char *function_name,
                      PyObject *(*create_input_object)(const InputType, size_t),
                      ReturnType (*convert_result)(PyObject *)) {
+  static bool cleanup_registered = false;
   if (!Py_IsInitialized()) {
     Py_Initialize();
     PyRun_SimpleString("import sys; sys.path.append('.')");
+    if (!cleanup_registered) {
```
Comment (erickcestari) [inline modules/pybitcoinkernel/module.cpp:25]: Do we need to have this variable/check?

**Review by erickcestari — CHANGES_REQUESTED** [review]
Thanks for creating the PR!!

**Comment by erickcestari** [comment]
Also we should have this cleanup in all python modules

File: modules/pybitcoinkernel/module.cpp (hunk 1 above)
Comment (KY-U) [reply modules/pybitcoinkernel/module.cpp:25]: It actually isn't necessary for now, if there is no reinitialization of `Py_Initialize()`, the "`if (!Py_IsInitialized())...`" block won't be called more than once.

I've added the check for a few reasons:
- It makes the intention of "registering cleanup routine **once**" explicit. Currently, that behavior is implicit.
- If in the future, for any reason, python reinitialization occurs in the same process, we'll already have preemptively avoided redundant callbacks to `atexit()`.
- No relevant cost.

The motivations are quite pedantic and can be ignored. If you prefer, I can remove that check from the commit.

**Comment by KY-U** [comment]
> Also we should have this cleanup in all python modules

Done!

If you think the `cleanup_registered` checks should be removed, just comment and I'll rebase again!

**Comment by erickcestari** [comment]
> > Also we should have this cleanup in all python modules
> 
> Done!
> 
> If you think the `cleanup_registered` checks should be removed, just comment and I'll rebase again!

It's only two lines. I think it's fine the way it is. Thanks!

**Review by erickcestari — APPROVED** [review]
ACK cbc6c890ed8a1e7f9fa9ae9fd3523fc246501988
